### PR TITLE
Admin Login logic

### PR DESCRIPTION
**Pull request by Lambu-here**
Edited the useraccount model to fit Django's Default backend user authentication model

-> Inherits AbstractUser from ...
-> renamed passwordhash => password
-> added groups and user_permissions to fit reverse relations in the AbstractUser class -> added default value to password, and unique field to username (Since Django's backend uses the username for default login)

Added Auth_User_Model and Authentication backends to settings.py

Added Login path to urls.py

Tweaked login.html and styles.css

### CODE REVIEW

**Comment by Lambu-here** [comment]
*Important*

login_view doesnt work with default database. The built in 'login' and 'authenticate' methods arent working with the database created. Please someone look into it

[Works on hardcoded values]

**Comment by Ashad001** [comment]
> _Important_
> 
> login_view doesnt work with default database. The built in 'login' and 'authenticate' methods arent working with the database created. Please someone look into it
> 
> [Works on hardcoded values]
> 
> @Ashad001

could you please create an issue about this on github..?

**Comment by Lambu-here** [comment]
> could you please create an issue about this on github..?

Alright 👍

**Review by Ashad001 — COMMENTED** [review]
@Lambu-here could you try pull the code again and add changes according to that pull, this one had alot of conflicts so ha to resolve them first, thank you!

**Comment by Lambu-here** [comment]
> @Lambu-here could you try pull the code again and add changes according to that pull, this one had alot of conflicts so ha to resolve them first, thank you!

can i go ahead an create a new PR and close this one?

**Pull request closed without merging**
