### PR TITLE
Django Models + Dummy Data

### PR DESCRIPTION
**Pull request by Lambu-here**
-> Django models created with reference to the relational diagram provided

-> Migrated the created models to the Database

-> Generated Dummy Data using Python Faker Script (registration/management/commands/create_dummy_data.py)

### CODE REVIEW

**Review by AyeshaIrshad1337 — APPROVED** [review]
Not any coflct found between branches , code review will be done by the heads

**Review by Ashad001 — APPROVED** [review]
LGTM!

**Review by AyeshaIrshad1337 — CHANGES_REQUESTED** [review]
this code has conflicted with the main branch code

**Comment by samaha-rizvi-4578** [comment]
conflict resolved

**Review by samaha-rizvi-4578 — APPROVED** [review]
approved

**Review by AyeshaIrshad1337 — COMMENTED** [review]
best all changes have been compiled

**Pull request merged**
